---
title: "openNCAreport Basic Walkthrough"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basic_walkthrough}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load package

```{r setup}
library(openNCAreport)
```

## Set input parameters

```{r params}
profile <- "SDEID"
tc_path <- system.file("test_data", package = "openNCAreport")
flag <- "FLGACCEPTKEL"
by <- "TREATXT"
```

## Loading a test case

```{r loadtc}
# TODO add more detail around tc class
tc <- load_test_case(tc_path)
```

## Assigning parameter labels

```{r labels}
tc <- tc %>% assign_wds_labels()
```

## Filter exclusions

```{r excl}
tc <- tc %>%
      filter_wds_exclusions(flg = flag,
                            profile = profile,
                            by = by)
```

## Select summary paramters

```{r select}
tc <- select_wds_pars(tc,
                      all_of(by),
                      AUCINFP,
                      AUCLAST,
                      AUC0..72,
                      CMAX1,
                      TMAX1,
                      THALF,
                      MRTP)
```

## Use {gtsummary} to produce exclusion and parameter summary and stack the tables for display

```{r gts}

Nn <- tc$exclusions %>%
      dplyr::select(-dplyr::all_of(profile)) %>%
      gtsummary::tbl_summary(by = dplyr::all_of(by),
                             type = list(EXCL ~ 'continuous'),
                             statistic = c(EXCL ~ "{length}, {little_n}"),
                             digits = c(EXCL ~ 0),
                             label = c(EXCL ~"N, n"))

gts_tab <- tc$WDS %>%
  gtsummary::tbl_summary(by = dplyr::all_of(by),
                         digits = list(TMAX1 ~ c(2, 1, 1),
                                       THALF ~ c(2, 1),
                                       MRTP ~ c(2, 1)),
                         statistic = c(
                            AUCINFP ~ "{gm_mean} ({gm_cv})",
                            AUCLAST ~ "{gm_mean} ({gm_cv})",
                            AUC0..72 ~ "{gm_mean} ({gm_cv})",
                            CMAX1 ~ "{gm_mean} ({gm_cv})",
                            TMAX1 ~ "{median} ({lower_range}-{upper_range})",
                            THALF ~ "{mean} &plusmn {sd}",
                            MRTP ~ "{mean} &plusmn {sd}"
                            )) %>%
  gtsummary::modify_footnote(dplyr::everything() ~ NA)

gtsummary::tbl_stack(list(Nn, gts_tab)) %>%
  gtsummary::as_gt() %>%
  gt::fmt(columns = dplyr::everything(), fns = function(x) x)
```
